image: python:3.8 # pega imagem de docker do python


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    
  only:
    - main

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  
  only:
    - main



stages:
  - build

build_main:
  stage: build
  script: # oq vai ser feito
    - cd module
    - python3 -m pip install --upgrade build
    - python3 -m build
    - python3 -m pip install .
   
  artifacts: # documentos e arquivos que serao gerados
    paths:
      - public
      
  only:
    - main
